camera0: "13051150"
camera1: "13051250"
frame_width: 640
frame_height: 640
mono_calibration_frames: 50
stereo_calibration_frames: 50
view_resize: 2
checkerboard_box_size_scale : 48
checkerboard_rows: 3
checkerboard_columns: 4
cooldown: 75
